set nocompatible
source $VIMRUNTIME/vimrc_example.vim
filetype off

set rtp+=~/vimfiles/bundle/Vundle.vim/
let path='~/vimfiles/bundle'
call vundle#begin(path)

Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set smarttab
set ruler
set nobackup
set number
set ignorecase
set smartcase
set hlsearch
set wildmenu
set mouse=a
set incsearch
set showcmd
set autoindent
set cursorline
set completeopt=longest,preview,menuone

au BufNewFile,BufRead *.gradle set filetype=groovy

call vundle#end() 
filetype plugin indent on
