[[ -z "$TMUX" ]] && exec tmux

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias vi="vim"
alias sbash="source $HOME/.bashrc"
alias vbash="vim $HOME/.mybashrc.sh"

export VISUAL=vim
export EDITOR=vim
export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[01;34m\] \w $(__git_ps1 "(%s)")\$\[\033[00m\] '
